export const categoriesArr = [
  'All',
  'Live',
  'Gaming',
  'Sketch comedy',
  'Music',
  'Off-roading',
  'Drifting',
  'Test Drives',
  'Personal luxury cars',
  'Television series',
  'Deep House',
  'Combat sports',
  'Racing video games',
  'Comedy',
  'Action-adventure games',
  'Pop Music',
  'Rapping',
  'Recently uploaded',
  'Watched',
];
